import { Note } from "../Types/Note";

export const notes: Note[] = [
  {
    id: '1',
    name: 'Creative Time',
    created: '2023-08-01',
    category: 'Personal',
    content: 'Sketch or paint for at least 45 minutes',
    date: '2023-08-01',
  },
  {
    id: '2',
    name: 'Call and Connect',
    created: '2023-08-02',
    category: 'Work',
    content: 'Review and respond to emails after lunch.',
    date: '2023-08-02',
  },
  {
    id: '3',
    name: 'Home Organization',
    created: '2023-08-03',
    category: 'Personal',
    content: 'Declutter the living room shelves.',
    date: '2023-08-03',
  },
  {
    id: '4',
    name: 'Work Tasks',
    created: '2023-08-04',
    category: 'Work',
    content: 'Schedule a meeting with the marketing team',
    date: '2023-08-04',
  },
  {
    id: '5',
    name: 'Personal Goals',
    created: '2023-08-05',
    category: 'Personal',
    content: 'Practice meditation for 15 minutes.',
    date: '2023-08-05',
  },
  {
    id: '6',
    name: 'Note 6',
    created: '2023-08-06',
    category: 'Work',
    content: 'This is the content of Note 6.',
    date: '2023-08-06',
  },
  {
    id: '7',
    name: 'Personal Goals',
    created: '2023-08-07',
    category: 'Personal',
    content: 'Go for a 30-minute jog in the morning.',
    date: '2023-08-07',
  },
]